# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='views',
        ),
    ]
